apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planka-postgres-data
  namespace: planka
  labels:
    app: planka-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
