apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planka-data
  namespace: planka
  labels:
    app: planka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
