service:
  annotations:
    metallb.io/loadBalancerIPs: 192.168.30.200
ports:
  web:
    forwardedHeaders:
      trustedIPs:
        - 192.168.30.0/24
        - 192.168.10.0/24
  websecure:
    forwardedHeaders:
      trustedIPs:
        - 192.168.30.0/24
        - 192.168.10.0/24
ingressClass:
  enabled: true
  isDefaultClass: true
